### PR TITLE
pr test

### PR DESCRIPTION
**Pull request by kruc**
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/kruc%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5284957%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/kruc/co-jemy/pull/2%23issuecomment-219775493%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-05-17T16%3A32%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2310778%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sethii%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%3Agun%3A%22%2C%20%22created_at%22%3A%20%222016-05-17T16%3A33%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2310778%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/sethii%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-05-17T16%3A37%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/5284957%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kruc%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/kruc/co-jemy/pull/2%23issuecomment-219775493%22%2C%20%22https%3A//github.com/kruc/co-jemy/pull/2%23issuecomment-219775706%22%2C%20%22https%3A//github.com/kruc/co-jemy/pull/2%23issuecomment-219776907%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/kruc'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/kruc/co-jemy/pull/2#issuecomment-219775493'>General Comment</a></b>
- <a href='https://github.com/sethii'></a> :shipit:
- <a href='https://github.com/sethii'></a> :shipit::gun:

<a href='https://www.codereviewhub.com/kruc/co-jemy/pull/2?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/kruc/co-jemy/pull/2?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/kruc/co-jemy/pull/2?approve=0'></a>&nbsp;<a href='https://github.com/kruc/co-jemy/pull/2'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by kruc** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/kruc/co-jemy/pull/2'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by sethii** [comment]
:shipit:

**Comment by sethii** [comment]
:shipit::gun:

**Comment by kruc** [comment]
:shipit:

**Pull request closed without merging**
